#!/usr/bin/env python3
"""
CSV to Graph CLI - Android Memory Metrics Visualization Tool

Reads metrics CSV files generated by run_log_usb.bat / run_log_wifi.bat
and generates time-series graphs with trend lines.
"""

import argparse
import sys
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates


DEFAULT_METRICS = ["native_heap_kb", "dalvik_heap_kb"]

METRIC_COLORS = {
    "native_heap_kb": "#2196F3",   # Blue
    "dalvik_heap_kb": "#4CAF50",   # Green
    "pss_kb": "#FF9800",           # Orange
    "graphics_kb": "#9C27B0",      # Purple
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate memory usage graphs from Android metrics CSV files.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python cli.py --input metrics.csv --output graph.pdf
  python cli.py --input metrics.csv --output graph.png --metrics native_heap_kb,dalvik_heap_kb
  python cli.py --input metrics.csv --output graph.pdf --no-trend
        """,
    )
    parser.add_argument(
        "--input", "-i",
        required=True,
        help="Path to input CSV file (metrics_*.csv)",
    )
    parser.add_argument(
        "--output", "-o",
        required=True,
        help="Path to output file (supports .png, .pdf)",
    )
    parser.add_argument(
        "--metrics", "-m",
        default=",".join(DEFAULT_METRICS),
        help=f"Comma-separated list of metrics to plot (default: {','.join(DEFAULT_METRICS)})",
    )
    parser.add_argument(
        "--no-trend",
        action="store_true",
        help="Disable trend lines",
    )
    parser.add_argument(
        "--title", "-t",
        default="Memory Usage Over Time",
        help="Graph title (default: 'Memory Usage Over Time')",
    )
    parser.add_argument(
        "--figsize",
        default="12,6",
        help="Figure size in inches as 'width,height' (default: 12,6)",
    )
    return parser.parse_args()


def load_csv(filepath: str) -> pd.DataFrame:
    """Load and preprocess the metrics CSV file."""
    df = pd.read_csv(filepath)

    # Parse iso_time column
    if "iso_time" not in df.columns:
        raise ValueError("CSV must contain 'iso_time' column")

    # Handle NA values in iso_time
    df = df[df["iso_time"] != "NA"].copy()

    # Parse datetime - handle various formats
    def parse_datetime(val):
        try:
            # Try ISO format with timezone
            return pd.to_datetime(val)
        except Exception:
            return pd.NaT

    df["datetime"] = df["iso_time"].apply(parse_datetime)
    df = df.dropna(subset=["datetime"])
    df = df.sort_values("datetime")

    return df


def calculate_trend(x_numeric: np.ndarray, y: np.ndarray):
    """
    Calculate linear regression trend line.
    Returns slope (rate of change) and fitted values.
    """
    # Remove NaN values
    mask = ~np.isnan(y)
    x_clean = x_numeric[mask]
    y_clean = y[mask]

    if len(x_clean) < 2:
        return None, None, None

    # Linear regression using numpy
    coeffs = np.polyfit(x_clean, y_clean, 1)
    slope = coeffs[0]
    fitted = np.polyval(coeffs, x_numeric)

    return slope, fitted, mask


def format_rate(slope_per_second: float) -> str:
    """
    Format the rate of change in human-readable format.
    Convert from KB/second to appropriate unit.
    """
    # Convert to KB per minute
    rate_per_min = slope_per_second * 60

    if abs(rate_per_min) < 1:
        # Show per hour if rate is very small
        rate_per_hour = rate_per_min * 60
        return f"{rate_per_hour:+.2f} KB/h"
    else:
        return f"{rate_per_min:+.2f} KB/min"


def generate_graph(
    df: pd.DataFrame,
    metrics: list[str],
    output_path: str,
    show_trend: bool = True,
    title: str = "Memory Usage Over Time",
    figsize: tuple[float, float] = (12, 6),
):
    """Generate the time-series graph with optional trend lines."""

    fig, ax = plt.subplots(figsize=figsize)

    # Convert datetime to numeric for trend calculation
    x_datetime = df["datetime"]
    x_numeric = (x_datetime - x_datetime.iloc[0]).dt.total_seconds().values

    for metric in metrics:
        if metric not in df.columns:
            print(f"Warning: Metric '{metric}' not found in CSV, skipping.", file=sys.stderr)
            continue

        # Get values, replacing 'NA' with NaN
        y = pd.to_numeric(df[metric], errors="coerce").values

        color = METRIC_COLORS.get(metric, None)

        # Plot actual data
        label = metric.replace("_kb", " (KB)").replace("_", " ").title()
        line, = ax.plot(x_datetime, y, label=label, color=color, linewidth=1.5)

        # Calculate and plot trend line
        if show_trend:
            slope, fitted, mask = calculate_trend(x_numeric, y)
            if slope is not None:
                rate_str = format_rate(slope)
                trend_label = f"{label} trend ({rate_str})"
                ax.plot(
                    x_datetime, fitted,
                    linestyle="--",
                    color=line.get_color(),
                    alpha=0.7,
                    linewidth=1,
                    label=trend_label,
                )

    # Formatting
    ax.set_xlabel("Time")
    ax.set_ylabel("Memory (KB)")
    ax.set_title(title)

    # Format x-axis dates
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
    ax.xaxis.set_major_locator(mdates.AutoDateLocator())

    # Rotate x-axis labels for better readability
    plt.xticks(rotation=45, ha="right")

    # Add grid
    ax.grid(True, alpha=0.3)

    # Legend
    ax.legend(loc="upper left", fontsize=9)

    # Tight layout to prevent label cutoff
    plt.tight_layout()

    # Save figure
    output_format = Path(output_path).suffix.lower().lstrip(".")
    if output_format not in ["png", "pdf"]:
        print(f"Warning: Unsupported format '{output_format}', defaulting to PNG", file=sys.stderr)
        output_format = "png"

    plt.savefig(output_path, format=output_format, dpi=150, bbox_inches="tight")
    plt.close()

    print(f"Graph saved to: {output_path}")


def main():
    args = parse_args()

    # Parse metrics
    metrics = [m.strip() for m in args.metrics.split(",")]

    # Parse figsize
    try:
        figsize = tuple(float(x) for x in args.figsize.split(","))
    except ValueError:
        print("Error: Invalid figsize format. Use 'width,height' (e.g., '12,6')", file=sys.stderr)
        sys.exit(1)

    # Load CSV
    try:
        df = load_csv(args.input)
    except FileNotFoundError:
        print(f"Error: File not found: {args.input}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    if df.empty:
        print("Error: No valid data rows found in CSV", file=sys.stderr)
        sys.exit(1)

    print(f"Loaded {len(df)} data points from {args.input}")

    # Generate graph
    generate_graph(
        df=df,
        metrics=metrics,
        output_path=args.output,
        show_trend=not args.no_trend,
        title=args.title,
        figsize=figsize,
    )


if __name__ == "__main__":
    main()
